### ISSUE TITLE
Feature Request: Triggered intents

### ISSUE THREAD

**Issue by litlfred** [dhis2/dhis2-android-trackercapture#76]
Hi,
I know this is probably the wrong place for this conversation, but I am not sure of the correct one.

We are exploring the use of DHIS2 Tracker for a couple of projects but a key thing we need is to trigger displaying locally stored training content (e.g. video, audio clips, html content) based on what stage someone is on in a program.  The content is intended for either the health worker or the client/patient.

We would like to use a second party platform for management of the training content and I was thinking we could use intents to link the dhis2 android app and the content platform.

Is there some possibility for providing support for this type of workflow?

Cheers,
-carl

**Comment by erlingfjelstad** [comment]
Hello,
We cannot implement this since we don't have the server support for it. If it would be available on the backend it will be very tricky to keep it in sync with our local database. If you want to do it, feel free to fork the project where you can pre-package that content with the app, and create custom view to show it in the app.

Regards,
Erling
